name: git-credential-github-apps
description: install git-credential-github-apps
inputs:
  image:
    description: oras image
    required: true
    default: ghcr.io/hakuyume/git-credential-github-apps:oras
  app-id:
    description: app id
    required: true
  private-key:
    description: private key
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      env:
        PRIVATE_KEY: ${{ inputs.private-key }}
      run: |
        TEMP=$(mktemp -d)

        oras pull --platform=linux/amd64 --output=${TEMP} ${{ inputs.image }}
        chmod +x ${TEMP}/git-credential-github-apps

        printenv PRIVATE_KEY > ${TEMP}/private-key
        git config --global --add credential.https://github.com.helper \
            "${TEMP}/git-credential-github-apps --app-id-from-literal=${{ inputs.app-id }} --private-key-from-file=${TEMP}/private-key"
        git config --global --replace-all credential.https://github.com.useHttpPath true

        git config --global --add url.https://github.com.insteadOf git@github.com:
