name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt -- --check
  cargo-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # https://github.com/actions/cache/blob/master/examples.md#rust---cargo
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo clippy -- --deny=warnings
  cargo-build:
    strategy:
      matrix:
        target:
          - linux-amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # https://github.com/actions/cache/blob/master/examples.md#rust---cargo
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: |
          sudo apt-get install --no-install-recommends --yes musl-tools
          rustup target add x86_64-unknown-linux-musl
          cargo build --release --target=x86_64-unknown-linux-musl
          upx target/x86_64-unknown-linux-musl/release/git-credential-github-apps
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: target/x86_64-unknown-linux-musl/release/git-credential-github-apps
  docker:
    if: github.ref == 'refs/heads/main'
    needs: cargo-build
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: linux-amd64
      - run: |
          cat << 'EOD' > Dockerfile
          FROM alpine
          RUN apk add --no-cache ca-certificates git git-lfs
          COPY --chmod=755 git-credential-github-apps /usr/local/bin/
          EOD
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/hakuyume/git-credential-github-apps:${{ github.sha }}
            ghcr.io/hakuyume/git-credential-github-apps
  oras:
    if: github.ref == 'refs/heads/main'
    needs: cargo-build
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: linux-amd64
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          oras push ghcr.io/hakuyume/git-credential-github-apps:${{ github.sha }}-oras git-credential-github-apps
          oras push ghcr.io/hakuyume/git-credential-github-apps:oras git-credential-github-apps
